# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Realm', '~> 2.6.2'


  # Pods for RealmDemo

  target 'RealmDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
